version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 127.0.0.1:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_HOST : 'db'
      POSTGRES_DATABASE: postgres1
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: newpassword
    restart: always
